[package]
name = "linguist-types"
version = "0.1.3"
edition = "2024"

description = "Type definitions for linguist crate"
license = "MIT"
repository = "https://github.com/drshade/linguist"

[dependencies]
serde = { version = "1", features = ["derive"] }
